# Generated by Django 6.0.2 on 2026-02-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
